version: "3.8"

services:
  docker-compose-demo:
    build:
      context: .
      args:
        JAR_FILE: sb-10-docker-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    ports:
      - 8890:8080
    environment:
      MYSQL_URL: jdbc:mysql://mysqlserver/docker_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  mysqlserver:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
    - 32223:3306
    volumes:
      - "sb-10-docker-mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
#      MYSQL_DATABASE: jwt

volumes:
  sb-10-docker-mysql-data: