spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=GMT%2B8&useSSl=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lcl123